registration_page:
    pattern:  /registration
    defaults: { _controller: MainBundle:Auth:registration }
    options:
        expose: true

login_page:
    pattern: /
    defaults: { _controller: MainBundle:Auth:login }
    options:
        expose: true

login_check:
    pattern: /login_check

forgotten_password:
    pattern: /forgotten_password
    defaults: { _controller: MainBundle:Auth:forgotPassword }

forgot_password_reset_success:
    pattern:  /reset_password_success
    defaults: { _controller: MainBundle:Auth:resetSuccess }

become_expert:
    pattern: /registration_expert
    defaults: { _controller: MainBundle:Auth:registrationExpert }

auth_account_activate:
    pattern: /auth/activate/{token}/{specific_password}
    defaults: { _controller: MainBundle:Auth:activateAccount }

auth_forgot_password_reset:
    pattern: /reset_password/{token}
    defaults: { _controller: MainBundle:Auth:passwordReset }