parameters:
#    domain_admin.example.class: Domain\AdminBundle\Example

services:
#    domain_admin.example:
#        class: %domain_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
