<?php

namespace Domain\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Domain\CoreBundle\Entity\Appointment;
use Domain\CoreBundle\Entity\User;

/**
 * AppointmentProblemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppointmentProblemRepository extends EntityRepository
{
    /**
     * Find problem by appointment and user
     * 
     * @param \Domain\CoreBundle\Entity\Appointment $appointment
     * @param \Domain\CoreBundle\Entity\User $user
     * @return \Domain\CoreBundle\Entity\Review
     */
    public function findByAppointmentAndUser(Appointment $appointment, User $user)
    {
        return $this->findOneBy([
            'appointment' => $appointment,
            'user' => $user,
        ]);
    }
}
