<?php

namespace Domain\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CompanyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompanyRepository extends EntityRepository
{

    /**
     * Get all companies (scalar) by Expert ids
     *
     * @param array $ids
     *
     * @return array|null
     */
    public function findAllByExpertIds(array $ids)
    {
        if (empty($ids)) {
            return null;
        }

        $qb = $this->createQueryBuilder('company');

        $qb
            ->select(
                'company.id as id, company.name as name, '
                .$qb->expr()->countDistinct('expert.id').' as experts_count'
            )
            ->leftJoin('company.experiences', 'experience')
            ->leftJoin('experience.expert', 'expert')
            ->groupBy('company.id')
            ->where(
                $qb->expr()->in('expert.id', ':ids')
            )
            ->setParameter('ids', $ids)
        ;



        return $qb->getQuery()->getScalarResult();

    }
}
