<?php

namespace Domain\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ExpertBillingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpertBillingRepository extends EntityRepository
{
    public function findOneActiveByExpert($expert)
    {
        return $this->findOneBy([
            'expert' => $expert,
            'active' => true
        ]);
    }
}
