<?php

namespace Domain\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * IndustryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IndustryRepository extends EntityRepository
{

    /**
     * Get all industries (scalar) by Expert ids
     *
     * @param array $ids
     *
     * @return array|null
     */
    public function findAllByExpertIds(array $ids)
    {
        if (empty($ids)) {
            return null;
        }

        $qb = $this->createQueryBuilder('industry');

        $qb
            ->select(
                'industry.id as id, industry.name as name, '
                .$qb->expr()->countDistinct('expert.id').' as experts_count'
            )
            ->leftJoin('industry.experts', 'expert')
            ->groupBy('industry.id')
            ->where(
                $qb->expr()->in('expert.id', ':ids')
            )
            ->setParameter('ids', $ids)
        ;



        return $qb->getQuery()->getScalarResult();

    }
}
