<?php

namespace Domain\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * NotificationOptionsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationOptionsRepository extends EntityRepository
{
}
