<?php

namespace Domain\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SkillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SkillRepository extends EntityRepository
{
    /**
     * Get existing skills by name
     *
     * @param array $names
     *
     * @return array
     */
    public function findByNames(array $names)
    {
        if (!count($names)) {
            return [];
        }

        $qb = $this->createQueryBuilder('s');
        $qb->where($qb->expr()->in('s.name', ':names'))
        ->setParameter('names', $names)
        ;

        return $qb->getQuery()->getResult();
    }
}
